package org.exceptionhandling.customexception;

public class Divide {

    public int divideNumber(int first, int second) throws ArithmeticException{
        return first / second;
    }
}
